### ISSUE TITLE
node range support

### ISSUE THREAD

**Issue by NickyDaB** [NickyDaB/CAST#15]
**Summary:**
support for node range. IE: node[001-100]

**Is your feature request related to a problem? Please describe.**
- frustrating to span a large block of nodes. 
- fernando request
- labs request
- issue: https://github.com/IBM/CAST/issues/222

**Describe the solution you'd like**
- support for the `node[001-100]` syntax
- a function to call that can be used across multiple APIs

**Additional context**
- there is a start of work for this feature on the https://github.com/NickyDaB/CAST/tree/R%26D-allocation_query_active_all branch in the `csmi/src/wm/cmd/allocation_create.c` file

**Issue Source:**
- issue: https://github.com/IBM/CAST/issues/222

**ToDo**:
- [x] first pass at getting something tangible working
- [x] there was some for this feature on the https://github.com/NickyDaB/CAST/tree/R%26D-allocation_query_active_all branch in the `csmi/src/wm/cmd/allocation_create.c` file. Move that to node_attributes_query for easier testing. 
- [x] copy into a function to call that can be used across multiple API cmd line wrappers
- [ ] go through apis that may need a node range, and call this function to add in support

**Comment by NickyDaB** [comment]
we did some of this work in some apis. but our official support for this atm is to use CSM APIs via python and use the xCAT link to communicate
