### ISSUE TITLE
RAS/UFM Integration

### ISSUE THREAD

**Issue by NickyDaB** [NickyDaB/CAST#16]
**Summary:**
eventual goal: fire a RAS event when something bad happens in UFM

**Is your feature request related to a problem? Please describe.**
- part of requirements from lab

**Describe the solution you'd like**
Have CSM log a RAS event when something bad happens in UFM

**Additional context**

**Issue Source:**
- lab request

**ToDo**:
- [x] Ask Mellanox, how can someone know that something bad has happened in UFM?
- [x] Mellanox said that UFM is generating many types of events (see Table 90: Supported Traps and Events at UFM User manual) that user can check and decide on the behavior accordingly. So, we need to look at that info and see if it points us in the right direction. 
- [x] saw a managed switch generate an event message after a fan was pulled.
- [x] unmanaged switch does not generate an event message after a fan was pulled.
- un managed switches provide limited event generation at a much larger time interval by default. and this number can be changed
- un managed switches will work at end of Nov. 
- [x] talk to john about linking the log message to BDS
- [x] fire a RAS event when something bad happens in UFM
- We want to update the password security of UFM restAPI CSM interaction:
- [x] SSL ask xCAT
