### ISSUE TITLE
Improvements to API logging Tools

### ISSUE THREAD

**Issue by NickyDaB** [NickyDaB/CAST#19]
**Summary:**
Improvements to API logging tools.

**ToDo:* 
- [x] set default log search location to the default install.
- [x] add feature to override that search location to a new directory should the user choose.
- [x] there seems to be a typo of "compute_stat" VS "computer_stat" please fix
