### ISSUE TITLE
Find job on node

### ISSUE THREAD

**Issue by NickyDaB** [NickyDaB/CAST#8]
New CSM API to find a job on a node.

**ToDo:**
- [x] Base functionality of node and a time range
- [x] s,S flags optionally independant
- [x] b,B flags
- [x] e,E flags
- [x] m,M flags
- [x] u flags
- [x] l flag
- [x] o flag
- [x] order by flags
- [x] non YAML, clean print option

**Example:**
```
csmdb_vm=# SELECT an.node_name, an.allocation_id, a.primary_job_id, a.user_name, a.num_nodes, a.begin_time, NULL as end_time 
FROM csm_allocation_node AS an
INNER JOIN csm_allocation AS a ON an.allocation_id = a.allocation_id 
WHERE (
node_name = 'c650f03p31-vm10' OR 
node_name = 'c650f03p31-vm04') 
UNION  
SELECT anh.node_name, anh.allocation_id, ah.primary_job_id, ah.user_name, ah.num_nodes, ah.begin_time, ah.end_time 
FROM csm_allocation_node_history AS anh
INNER JOIN csm_allocation_history AS ah ON anh.allocation_id = ah.allocation_id 
WHERE (
node_name = 'c650f03p31-vm10' OR 
node_name = 'c650f03p31-vm04') 
ORDER BY node_name, allocation_id ASC NULLS LAST;
    node_name    | allocation_id | primary_job_id | user_name | num_nodes |         begin_time         |          end_time          
-----------------+---------------+----------------+-----------+-----------+----------------------------+----------------------------
 c650f03p31-vm04 |             2 |              1 | root      |         3 | 2012-01-10 15:49:29.183549 | 
 c650f03p31-vm10 |             3 |              2 | root      |         3 | 2012-01-10 16:00:09.001173 | 2012-01-16 17:59:43.784577
 c650f03p31-vm10 |             4 |              4 | root      |         3 | 2012-01-10 16:12:12.434493 | 
(3 rows)
```
